services:
  - type: web
    name: veritas-ai-backend
    runtime: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn api.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_OYu8GxlLbJ0q@ep-gentle-glitter-aif8rkh9-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        value: veritas-dev-secret-key-change-in-production
      - key: SENDGRID_API_KEY
        value: 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
      - key: OLLAMA_API_KEY
        value: aa79d579db464cb382bfa44c282cc694.g4URw6ipGwlWTcxyeu7krhCp
      - key: OLLAMA_URL
        value: https://ai-agent-vgaq.onrender.com
